create extension if not exists "uuid-ossp";
create table public.products (id uuid primary key default uuid_generate_v4(), name text not null, slug text unique not null, description text, price integer not null check(price>=0), compare_at_price integer, category text not null, images jsonb not null default '[]', sizes jsonb not null default '[]', colors jsonb not null default '[]', sku text unique, stock integer not null default 0 check(stock>=0), is_active boolean not null default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.customers (id uuid primary key references auth.users(id) on delete cascade, name text, email text unique, phone text, created_at timestamptz default now());
create table public.orders (id uuid primary key default uuid_generate_v4(), customer_id uuid references public.customers(id), customer_name text not null, email text not null, phone text not null, address text not null, city text not null, state text not null, pincode text not null, subtotal integer not null, shipping_fee integer not null default 0, discount integer not null default 0, total integer not null, payment_status text not null default 'PENDING_PAYMENT' check(payment_status in ('PENDING_PAYMENT','PAID','FAILED','REFUNDED')), order_status text not null default 'PENDING_PAYMENT' check(order_status in ('PENDING_PAYMENT','PAID','PROCESSING','SHIPPED','OUT_FOR_DELIVERY','DELIVERED','CANCELLED','REFUNDED')), razorpay_order_id text unique, razorpay_payment_id text unique, tracking_number text, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.order_items (id uuid primary key default uuid_generate_v4(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id), product_name text not null, product_image text, size text, color text, quantity integer not null check(quantity>0), price integer not null);
create table public.newsletter_subscribers (id uuid primary key default uuid_generate_v4(), email text unique not null, created_at timestamptz default now());
create table public.contact_submissions (id uuid primary key default uuid_generate_v4(), name text not null, email text not null, message text not null, created_at timestamptz default now());
create index orders_email_phone_idx on public.orders(email,phone); create index products_category_idx on public.products(category) where is_active=true;
alter table public.products enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.customers enable row level security; alter table public.newsletter_subscribers enable row level security;
create policy "public read active products" on public.products for select using (is_active=true);
create policy "customers read own orders" on public.orders for select using (auth.uid()=customer_id);
create policy "customers read own profile" on public.customers for select using (auth.uid()=id);
create policy "customers update own profile" on public.customers for update using (auth.uid()=id);
-- Use a service-role Edge Function for checkout, payment verification, webhooks, subscriptions, admin actions and inventory writes. Never allow browser clients to write orders directly.
